name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ "8.1", "8.2" ]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run test suite
        run: vendor/bin/pest --fail-on-warning